name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  myjob:
     uses: gowthamshankar99/github-actions/.github/workflows/test.yaml@main

  terraformjob:
     uses: gowthamshankar99/new-terraform-action/.github/workflows/terraform-static-code-analysis.yaml@main
        
  
